# Site settings
# in the templates available like {{ site.myvariable }}.
title: Céline's portfolio
email: celine.leuzinger@outlook.com
brand: Céline Leuzinger
headline: NLP engineer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://celinenausicaa.github.io/celinenausicaa/" # the base hostname & protocol for your site
copyright: 2023 Céline Leuzinger, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: celine.leuzinger@outlook.com
phone: +44 (0)7597 692048

# Tracking
googleAnalitycsID: UA-83933844-1

